version: "3.5"
services:
    mariadb:
        image: mariadb:10.9.3
        container_name: "mariadb-Warehouse"
        restart: on-failure    
        environment:
            - MYSQL_ROOT_PASSWORD=lok         
        volumes:
            - ./mariadb/data:/var/lib/mysql
        ports:
            - 33070:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --lower_case_table_names=1
        networks:
            - WarehouseSystem
  

networks:
    WarehouseSystem:
        name: WarehouseSystem